WITH v(name, code, region) AS (VALUES 
    ("Agrigento","AG","Sicilia"),
    ("Alessandria","AL","Piemonte"),
    ("Ancona","AN","Marche"),
    ("Arezzo","AR","Toscana"),
    ("Ascoli Piceno","AP","Marche"),
    ("Asti","AT","Piemonte"),
    ("Avellino","AV","Campania"),
    ("Bari","BA","Puglia"),
    ("Barletta-Andria-Trani","BT","Puglia"),
    ("Belluno","BL","Veneto"),
    ("Benevento","BN","Campania"),
    ("Bergamo","BG","Lombardia"),
    ("Biella","BI","Piemonte"),
    ("Bologna","BO","Emilia-Romagna"),
    ("Bolzano","BZ","Trentino-Alto Adige"),
    ("Brescia","BS","Lombardia"),
    ("Brindisi","BR","Puglia"),
    ("Cagliari","CA","Sardegna"),
    ("Caltanissetta","CL","Sicilia"),
    ("Campobasso","CB","Molise"),
    ("Caserta","CE","Campania"),
    ("Catania","CT","Sicilia"),
    ("Catanzaro","CZ","Calabria"),
    ("Chieti","CH","Abruzzo"),
    ("Como","CO","Lombardia"),
    ("Cosenza","CS","Calabria"),
    ("Cremona","CR","Lombardia"),
    ("Crotone","KR","Calabria"),
    ("Cuneo","CN","Piemonte"),
    ("Enna","EN","Sicilia"),
    ("Fermo","FM","Marche"),
    ("Ferrara","FE","Emilia-Romagna"),
    ("Firenze","FI","Toscana"),
    ("Foggia","FG","Puglia"),
    ("Forlì-Cesena","FC","Emilia-Romagna"),
    ("Frosinone","FR","Lazio"),
    ("Gallura Nord-Est Sardegna","OT","Sardegna"),
    ("Genova","GE","Liguria"),
    ("Gorizia","GO","Friuli-Venezia Giulia"),
    ("Grosseto","GR","Toscana"),
    ("Imperia","IM","Liguria"),
    ("Isernia","IS","Molise"),
    ("L'Aquila","AQ","Abruzzo"),
    ("La Spezia","SP","Liguria"),
    ("Latina","LT","Lazio"),
    ("Lecce","LE","Puglia"),
    ("Lecco","LC","Lombardia"),
    ("Livorno","LI","Toscana"),
    ("Lodi","LO","Lombardia"),
    ("Lucca","LU","Toscana"),
    ("Macerata","MC","Marche"),
    ("Mantova","MN","Lombardia"),
    ("Massa-Carrara","MS","Toscana"),
    ("Matera","MT","Basilicata"),
    ("Medio Campidano","VS","Sardegna"),
    ("Messina","ME","Sicilia"),
    ("Milano","MI","Lombardia"),
    ("Modena","MO","Emilia-Romagna"),
    ("Monza e della Brianza","MB","Lombardia"),
    ("Napoli","NA","Campania"),
    ("Novara","NO","Piemonte"),
    ("Nuoro","NU","Sardegna"),
    ("Ogliastra","OG","Sardegna"),
    ("Oristano","OR","Sardegna"),
    ("Padova","PD","Veneto"),
    ("Palermo","PA","Sicilia"),
    ("Parma","PR","Emilia-Romagna"),
    ("Pavia","PV","Lombardia"),
    ("Perugia","PG","Umbria"),
    ("Pesaro e Urbino","PU","Marche"),
    ("Pescara","PE","Abruzzo"),
    ("Piacenza","PC","Emilia-Romagna"),
    ("Pisa","PI","Toscana"),
    ("Pistoia","PT","Toscana"),
    ("Pordenone","PN","Friuli-Venezia Giulia"),
    ("Potenza","PZ","Basilicata"),
    ("Prato","PO","Toscana"),
    ("Ragusa","RG","Sicilia"),
    ("Ravenna","RA","Emilia-Romagna"),
    ("Reggio Calabria","RC","Calabria"),
    ("Reggio nell'Emilia","RE","Emilia-Romagna"),
    ("Rieti","RI","Lazio"),
    ("Rimini","RN","Emilia-Romagna"),
    ("Roma","RM","Lazio"),
    ("Rovigo","RO","Veneto"),
    ("Salerno","SA","Campania"),
    ("Sassari","SS","Sardegna"),
    ("Savona","SV","Liguria"),
    ("Siena","SI","Toscana"),
    ("Siracusa","SR","Sicilia"),
    ("Sondrio","SO","Lombardia"),
    ("Sulcis Iglesiente","CI","Sardegna"),
    ("Taranto","TA","Puglia"),
    ("Teramo","TE","Abruzzo"),
    ("Terni","TR","Umbria"),
    ("Torino","TO","Piemonte"),
    ("Trapani","TP","Sicilia"),
    ("Trento","TN","Trentino-Alto Adige"),
    ("Treviso","TV","Veneto"),
    ("Trieste","TS","Friuli-Venezia Giulia"),
    ("Udine","UD","Friuli-Venezia Giulia"),
    ("Aosta","AO","Valle d'Aosta"),
    ("Varese","VA","Lombardia"),
    ("Venezia","VE","Veneto"),
    ("Verbano-Cusio-Ossola","VB","Piemonte"),
    ("Vercelli","VC","Piemonte"),
    ("Verona","VR","Veneto"),
    ("Vibo Valentia","VV","Calabria"),
    ("Vicenza","VI","Veneto"),
    ("Viterbo","VT","Lazio"))
INSERT OR IGNORE INTO provinces (name, code, region_id)
SELECT v.name, v.code, r.id 
FROM v JOIN regions AS r ON r.name = v.region